name: anime
description: Flutter Anime app

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^10.1.2
  http: ^1.1.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/src/data/dummy_json/
